### ISSUE TITLE
DPI is not handled correctly

### ISSUE THREAD

**Issue by fgravin** [camptocamp/inkmap#12]
DPI should change the accuracy of the print, not the extent.

Same spec with

**50 dpi**
![received](https://user-images.githubusercontent.com/1491924/101759013-59923380-3ad9-11eb-8e51-af65bbf3b6e6.png)

**300 dpi**
![expected](https://user-images.githubusercontent.com/1491924/101759020-5bf48d80-3ad9-11eb-901d-1982a66a563a.png)

**Comment by jahow** [comment]
This should only happen when specifying a size in pixels. Closing
