### ISSUE TITLE
Incorrect documentation for PrintStatus

### ISSUE THREAD

**Issue by jussih** [camptocamp/inkmap#54]
The documentation states the following:

<h4 dir="auto"><code>PrintStatus</code> type</h4>
<p dir="auto">A <code>PrintStatus</code> object describes the status of a print job.</p>

field | type | description
-- | -- | --
id | number | Job id.
progress | number | Job progress, from 0 to 1.
status | string | Either 'pending', 'ongoing', 'finished' or 'canceled'.
resultImageUrl | string | An URL used to access the print result (PNG image). This will only be available once the job status is 'finished'.

The actual PrintStatus emitted by the observable returned from `getJobStatus([id])` looks like the following. `imageBlob` is null until the operation is finished.

```
{
  id: 0
  ​imageBlob: Blob { size: 4012847, type: "image/png" }
  ​progress: 1
  ​sourceLoadErrors: Array []
  ​spec: Object { dpi: 300, scale: 3260.5795017802066, projection: "EPSG:3067", … }
  ​status: "finished"
}
```

**Comment by jahow** [comment]
That's right, the API doc is currently made by hand and it is no surprise that it contains errors... Would you be able to issue a pull request for this?
